### ISSUE TITLE
Documentation is not accessible

### ISSUE THREAD

**Issue by barnabaskecskes** [Fenzland/Laroute#1]
<img width="276" alt="screen shot 2016-11-05 at 14 09 00" src="https://cloud.githubusercontent.com/assets/3535449/20030662/9128b45e-a361-11e6-9f6f-a954e5cfdddd.png">

**Comment by Fenzland** [comment]
Thank you. I'm writing it. It will accessible several hours later.

**Comment by Fenzland** [comment]
Now it's accessible.
